In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import time
import pickle

from tqdm import tqdm
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
print(os.getcwd())
os.chdir("/content/drive/My Drive/Uni Projects/Anomaly Detection using Ensembles/Experiments/")
print(os.getcwd())

/content
/content/drive/My Drive/Uni Projects/Anomaly Detection using Ensembles/Experiments


In [ ]:
from models.models import MnistModel

In [ ]:
model0 = MnistModel()
classifier0 = model0.build()
classifier0 = model0.load_model("models/classifier0")

model1 = MnistModel()
classifier1 = model1.build()
classifier1 = model1.load_model("models/classifier1")

model2 = MnistModel()
classifier2 = model2.build()
classifier2 = model2.load_model("models/classifier2")

model3 = MnistModel()
classifier3 = model3.build()
classifier3 = model3.load_model("models/classifier3")

model4 = MnistModel()
classifier4 = model4.build()
classifier4 = model4.load_model("models/classifier4")

model5 = MnistModel()
classifier5 = model5.build()
classifier5 = model5.load_model("models/classifier5")

model6 = MnistModel()
classifier6 = model6.build()
classifier6 = model6.load_model("models/classifier6")

model7 = MnistModel()
classifier7 = model7.build()
classifier7 = model7.load_model("models/classifier7")

model8 = MnistModel()
classifier8 = model8.build()
classifier8 = model8.load_model("models/classifier8")

In [ ]:
pickle_in = open("pre-defined/mnist_data_wo9.pickle","rb")
x_train, y_train, x_val, y_val, x_test, y_test = pickle.load(pickle_in)

In [ ]:
pickle_in = open("pre-defined/temperature_value.pickle","rb")
temp_value = pickle.load(pickle_in)

In [ ]:
temp_value

[<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.6913705>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.647186>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.697141>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.7036467>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.6812327>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.7035344>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.6817927>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.6865652>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.6931825>]

  

*   **wot - Without temperature scaling**
*   **wt - With temperature scaling bold text**
  

In [ ]:
pickle_in = open("pre-defined/reference_vector.pickle","rb")
ref_vec_wot_in, ref_vec_wt_in = pickle.load(pickle_in)

In [ ]:
pickle_in = open("pre-defined/reference_vector_ood.pickle","rb")
ref_vec_wot_ood, ref_vec_wt_ood = pickle.load(pickle_in)

Calculating reference value for anomaly data(Which is class 9 in this case)

In [ ]:
max_sm_9 = []
for data, label in zip(x_test, y_test):
  ref_value = []
  if label == 9:
    img = data.reshape([-1, 28, 28, 1])
    max0 = model0.get_max_pred_value(img)
    max1 = model1.get_max_pred_value(img)
    max2 = model2.get_max_pred_value(img)
    max3 = model3.get_max_pred_value(img)
    max4 = model4.get_max_pred_value(img)
    max5 = model5.get_max_pred_value(img)
    max6 = model6.get_max_pred_value(img)
    max7 = model7.get_max_pred_value(img)
    max8 = model8.get_max_pred_value(img)
    ref_value =[max0, max1, max2, max3, max4, max5, max6, max7, max8]
    max_sm_9.append(ref_value)


In [ ]:
len(max_sm_9)

1009

Calculating reference value for anomaly data(Which is class 9 in this case) - with temperature scaling

In [ ]:
max_sm_9_wt = []
for data, label in zip(x_test, y_test):
  ref_value = []
  if label == 9:
    img = data.reshape([-1, 28, 28, 1])
    max0 = model0.get_max_pred_value(img, temp=temp_value[0])
    max1 = model1.get_max_pred_value(img, temp=temp_value[1])
    max2 = model2.get_max_pred_value(img, temp=temp_value[2])
    max3 = model3.get_max_pred_value(img, temp=temp_value[3])
    max4 = model4.get_max_pred_value(img, temp=temp_value[4])
    max5 = model5.get_max_pred_value(img, temp=temp_value[5])
    max6 = model6.get_max_pred_value(img, temp=temp_value[6])
    max7 = model7.get_max_pred_value(img, temp=temp_value[7])
    max8 = model8.get_max_pred_value(img, temp=temp_value[8])
    ref_value =[max0, max1, max2, max3, max4, max5, max6, max7, max8]
    max_sm_9_wt.append(ref_value)

In [ ]:
max_sm_9_wt[:10]

[[0.7282372,
  0.6259887,
  0.60143745,
  0.54150105,
  0.53384936,
  0.868745,
  0.42317793,
  0.65550625,
  0.5436436],
 [0.9068485,
  0.7181782,
  0.9516882,
  0.8890306,
  0.6782604,
  0.7617969,
  0.91773295,
  0.49823907,
  0.9960444],
 [0.52072984,
  0.3982336,
  0.6445526,
  0.6179431,
  0.93363595,
  0.7474672,
  0.76092285,
  0.8388344,
  0.65553695],
 [0.74013823,
  0.4362718,
  0.62224334,
  0.73365694,
  0.9513711,
  0.5161773,
  0.53444695,
  0.79498196,
  0.6072545],
 [0.7839103,
  0.6397574,
  0.5789713,
  0.5102658,
  0.70571876,
  0.5664226,
  0.6350228,
  0.8882915,
  0.6324284],
 [0.7120871,
  0.51529396,
  0.619812,
  0.9445901,
  0.83005095,
  0.62065226,
  0.8735189,
  0.7869777,
  0.5943536],
 [0.6185703,
  0.58598065,
  0.831141,
  0.70016927,
  0.938048,
  0.45931935,
  0.6809184,
  0.87417066,
  0.8444062],
 [0.54770523,
  0.6774922,
  0.60910666,
  0.65900624,
  0.8308049,
  0.68494415,
  0.5252438,
  0.8937425,
  0.9893008],
 [0.60604745,
  0.60625064,
  0.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
ref_vec_wot_in

[0.9940913297361088,
 0.9943297851623129,
 0.9950363865816765,
 0.994762285760556,
 0.9929170314438901,
 0.994529322409794,
 0.994572611424617,
 0.9955482242357492,
 0.9964404718016846]

In [ ]:
ref_vec_wot_ood

[0.9002593521664782,
 0.8484015442948687,
 0.9038626482474912,
 0.9129432007682527,
 0.8917978708162132,
 0.9136694506140652,
 0.8778718607685333,
 0.8957953839198403,
 0.8886791465642699]

In [ ]:
ref_vec_wt_in

[0.9729726480980094,
 0.9762566529240282,
 0.9769669794804251,
 0.9763545533288605,
 0.9702818720122461,
 0.9753097152337623,
 0.9762728177982828,
 0.9761019294529255,
 0.9817767171972779]

In [ ]:
ref_vec_wt_ood

[0.7404742626639885,
 0.5984857454108148,
 0.7515997397909472,
 0.7743498120635772,
 0.7199994130967687,
 0.7822494414184806,
 0.6910225863640125,
 0.7354823900305707,
 0.708852559113037]

**Cosine Similarity**

In [ ]:
sim_in = cosine_similarity(max_sm_9_wt, [ref_vec_wt_in])
sim_ood = cosine_similarity(max_sm_9_wt, [ref_vec_wt_ood])

In [ ]:
sim_in

array([[0.98082577],
       [0.98326656],
       [0.97533566],
       ...,
       [0.98835119],
       [0.98374023],
       [0.99817477]])

In [ ]:
sim_ood

array([[0.98316826],
       [0.98215309],
       [0.9798862 ],
       ...,
       [0.98676611],
       [0.98931194],
       [0.99602948]])

In [ ]:
len(max_sm_9_wt)

1009

In [ ]:
accuracy = 0.0
for si, so in zip(sim_in[0], sim_ood[0]):
  if so > si:
    accuracy = accuracy + 1

print("Accuracy: ", accuracy/len(max_sm_9_wt))

Accuracy:  0.0009910802775024777


In [ ]:
max_sm_9_wt[0]

[0.7282372,
 0.6259887,
 0.60143745,
 0.54150105,
 0.53384936,
 0.868745,
 0.42317793,
 0.65550625,
 0.5436436]

**Cross Corelation**

In [ ]:
np.correlate(max_sm_9_wt[0], ref_vec_wt_ood)

array([4.00908621])

In [ ]:
cc

array([5.38795655])

In [ ]:
accuracy = 0.0
for data in max_sm_9_wt:
  cc_ood = np.correlate(data, ref_vec_wt_ood)
  cc_in = np.correlate(data, ref_vec_wt_in)
  print(cc_ood, cc_in)
  if cc_ood < cc_in:
    accuracy = accuracy + 1

print("Accuracy: ", accuracy/len(max_sm_9_wt))

[4.00908621] [5.38795655]
[5.29595779] [7.14251672]
[4.45123886] [5.96862142]
[4.31817088] [5.79073662]
[4.28526719] [5.79623249]
[4.71985164] [6.33888843]
[4.7223207] [6.37474001]
[4.63466864] [6.26339444]
[4.41252436] [5.95813727]
[5.66089738] [7.64168377]
[4.112049] [5.51866984]
[4.128857] [5.53668751]
[4.61304512] [6.17548208]
[3.28584196] [4.42618086]
[4.84293414] [6.51134129]
[4.96784779] [6.67172913]
[5.73238828] [7.7192883]
[3.16951838] [4.3125556]
[5.79255411] [7.82528547]
[5.57797527] [7.52072356]
[3.98435084] [5.39998568]
[4.50217425] [6.11688478]
[4.57604719] [6.15501217]
[4.15697402] [5.64762141]
[3.40580604] [4.65567223]
[5.87328765] [7.94180084]
[4.09600932] [5.51280205]
[4.19961576] [5.7114253]
[5.50029422] [7.42475209]
[3.78989921] [5.15888686]
[5.40827661] [7.30635732]
[3.7727074] [5.04501809]
[4.65803639] [6.28170382]
[5.23176784] [7.0848384]
[4.7291257] [6.36998062]
[3.69680819] [5.03721092]
[3.98921038] [5.41372515]
[5.20277886] [6.99832288]
[4.53032502] [6.1035679

**Euclidean Distances**

In [ ]:
np.linalg.norm(np.array(max_sm_9_wt[0]) - np.array(ref_vec_wt_ood)) 

0.47459213656866905

In [ ]:
np.linalg.norm(np.array(max_sm_9_wt[0]) - np.array(ref_vec_wt_in)) 

1.1468167285160065

In [ ]:
accuracy = 0.0
for data in max_sm_9_wt:
  dist_ood = np.linalg.norm(np.array(data) - np.array(ref_vec_wt_ood)) 
  dist_in = np.linalg.norm(np.array(data) - np.array(ref_vec_wt_in))

  sim_in = 1 / (1 + dist_in)
  sim_ood = 1 / (1 + dist_ood)

  #if dist_ood < dist_in:
  if sim_ood > sim_in:
    accuracy = accuracy + 1

print("Accuracy: ", accuracy/len(max_sm_9_wt)) 

Accuracy:  0.8453914767096135


In [ ]:
ind = 1
ood = 0

Calculating reference value for all data including anomaly data(Which is class 9 in this case)

In [ ]:
max_sm_all_wt = []
for data, label in zip(x_test, y_test):
  img = data.reshape([-1, 28, 28, 1])
  ref_value = []
  
  if label == 9:
    lbl = ood
  else:
    lbl = ind

  max0 = model0.get_max_pred_value(img, temp=temp_value[0])
  max1 = model1.get_max_pred_value(img, temp=temp_value[1])
  max2 = model2.get_max_pred_value(img, temp=temp_value[2])
  max3 = model3.get_max_pred_value(img, temp=temp_value[3])
  max4 = model4.get_max_pred_value(img, temp=temp_value[4])
  max5 = model5.get_max_pred_value(img, temp=temp_value[5])
  max6 = model6.get_max_pred_value(img, temp=temp_value[6])
  max7 = model7.get_max_pred_value(img, temp=temp_value[7])
  max8 = model8.get_max_pred_value(img, temp=temp_value[8])
  ref_value =[max0, max1, max2, max3, max4, max5, max6, max7, max8]
  max_sm_all_wt.append([ref_value, lbl])

In [ ]:
max_sm_all_wt[:10]

[[[0.9996635,
   0.99907,
   0.99841535,
   0.99993634,
   0.99576217,
   0.99980515,
   0.9995629,
   0.9505187,
   0.9999871],
  1],
 [[0.99973077,
   0.9999821,
   0.9981012,
   0.99980944,
   0.99950325,
   0.99978465,
   0.9999782,
   0.99974316,
   0.99996257],
  1],
 [[0.9871345,
   0.29657838,
   0.9722617,
   0.96506464,
   0.975541,
   0.9677563,
   0.9748619,
   0.9481775,
   0.98541045],
  1],
 [[0.8109226,
   0.99877733,
   0.997799,
   0.99982136,
   0.99857867,
   0.9995665,
   0.99890697,
   0.9997937,
   0.9996486],
  1],
 [[0.9995042,
   0.9999579,
   0.99994695,
   0.999959,
   0.7102692,
   0.999967,
   0.9999193,
   0.99987006,
   0.9999908],
  1],
 [[0.98308957,
   0.33129182,
   0.9733879,
   0.9753666,
   0.9699472,
   0.9679215,
   0.97146726,
   0.9505859,
   0.96980065],
  1],
 [[0.9404348,
   0.8590928,
   0.9850493,
   0.9492639,
   0.9363611,
   0.94847673,
   0.8798015,
   0.94439816,
   0.99945134],
  1],
 [[0.7282372,
   0.6259887,
   0.60143745,
   0.5

In [ ]:
accuracy = 0.0
count_in = 0
count_ood = 0
acc_in = 0.0
acc_ood = 0.0

for data, lbl in max_sm_all_wt:
  dist_ood = np.linalg.norm(np.array(data) - np.array(ref_vec_wt_ood)) 
  dist_in = np.linalg.norm(np.array(data) - np.array(ref_vec_wt_in))

  sim_in = 1 / (1 + dist_in)
  sim_ood = 1 / (1 + dist_ood)

  #if dist_ood < dist_in:
  if lbl == ind:
    count_in = count_in + 1
    if sim_in > sim_ood:
      accuracy = accuracy + 1
      acc_in = acc_in + 1
  else:  
    count_ood = count_ood + 1
    if sim_ood > sim_in:
      accuracy = accuracy + 1
      acc_ood = acc_ood + 1

print("Total Accuracy: ", accuracy/len(max_sm_all_wt)) 
print("Accuracy of determining ID data: ", acc_in/count_in)
print("Accuracy of determining OOD data: ", acc_ood/count_ood)

Total Accuracy:  0.9362
Accuracy of determining ID data:  0.9463908352797241
Accuracy of determining OOD data:  0.8453914767096135
